General:
    TOKEN: "" # bot token
    ACTIVITY: "listening" # playing, watching, listening, streaming
    DOING_ACTIVITY: "Tweets" # what you want the bot to be playing, watching, or listening
    STREAMING_ACTIVITY_TWITCH_URL: "" # twitch url if ACTIVITY is "streaming"
    STATUS: "online" # online, idle, dnd, invisible
    GUILD_ID: 1234 # guild id for the server
    EMBED_COLOR: "#9C27B0" # hex color code for embeds

Roles:
    ON_JOB_ROLE_ID: 1234 # ping role id

Listening_Categories:
    - 1234 # listening categories

Keyword_Categories:
    - 1234 # keyword categories